name: Deploy Multiple Apps to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      #2.1 Setup Google access
      - name: Set up Google credentials
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > $HOME/gcloud.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud.json"

      # 3. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4. Clear npm cache
      - name: Clear npm cache
        run: npm cache clean --force

      # 5. Build Angular Host App
      - name: Build Angular Host App
        run: |
          cd angular-host-app
          npm install --force
          npm run build
          cd ..

      # 6. Build Angular Remote App
      - name: Build Angular Remote App
        run: |
          cd angular-remote-app
          npm install --force
          npm run build
          cd ..

      # 7. Build React Host App
      # - name: Build React Host App
      #   run: |
      #       cd react-host-app
      #       npm install --force
      #       SKIP_PREFLIGHT_CHECK=true npm run build
      #       cd ..

      # # 8. Build React Remote App
      # - name: Build React Remote App
      #   run: |
      #     cd react-remote-app
      #     npm install --force
      #     SKIP_PREFLIGHT_CHECK=true npm run build
      #     cd ..

      # 9. Build Vue Host App
      - name: Build Vue Host App
        run: |
          cd vue-host-app
          npm install --force
          npm run build
          cd ..

      # 10. Build Vue Remote App
      - name: Build Vue Remote App
        run: |
          cd vue-remote-app
          npm install --force
          npm run build
          cd ..

      # 11. Deploy Angular Host App
      - name: Deploy Angular Host App
        run: firebase deploy --only hosting:angularHostApp 

      # 12. Deploy Angular Remote App
      - name: Deploy Angular Remote App
        run: firebase deploy --only hosting:angularRemoteApp

      # 13. Deploy React Host App
      # - name: Deploy React Host App
      #   run: firebase deploy --only hosting:reactHostApp --token ${{ secrets.FIREBASE_TOKEN }}

      # # 14. Deploy React Remote App
      # - name: Deploy React Remote App
      #   run: firebase deploy --only hosting:reactRemoteApp --token ${{ secrets.FIREBASE_TOKEN }}

      # 15. Deploy Vue Host App
      - name: Deploy Vue Host App
        run: firebase deploy --only hosting:vueHostApp

      # 16. Deploy Vue Remote App
      - name: Deploy Vue Remote App
        run: firebase deploy --only hosting:vueRemoteApp
