name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: angular-host-app 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}      # GitHub token, needed for PR comments and status
          firebaseToken: ${{ secrets.FIREBASE_TOKEN }} # Firebase CLI token created via firebase login:ci
          channelId: live                             # or remove if deploying to default hosting channel
          projectId: microfe-angular-host             # Your Firebase project ID
