name: Deploy Multiple Apps to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud.json

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Write Service Account JSON to file
      - name: Set up Google credentials
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > $GOOGLE_APPLICATION_CREDENTIALS

      # 4. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5. Clear npm cache
      - name: Clear npm cache
        run: npm cache clean --force

      # 6. Build Angular Host App
      - name: Build Angular Host App
        run: |
          cd angular-host-app
          npm install --force
          npm run build
          cd ..

      # 7. Build Angular Remote App
      - name: Build Angular Remote App
        run: |
          cd angular-remote-app
          npm install --force
          npm run build
          cd ..

      # 8. Build Vue Host App
      - name: Build Vue Host App
        run: |
          cd vue-host-app
          npm install --force
          npm run build
          cd ..

      # 9. Build Vue Remote App
      - name: Build Vue Remote App
        run: |
          cd vue-remote-app
          npm install --force
          npm run build
          cd ..

      # (Optional) React Host App
      # - name: Build React Host App
      #   run: |
      #     cd react-host-app
      #     npm install --force
      #     SKIP_PREFLIGHT_CHECK=true npm run build
      #     cd ..

      # (Optional) React Remote App
      # - name: Build React Remote App
      #   run: |
      #     cd react-remote-app
      #     npm install --force
      #     SKIP_PREFLIGHT_CHECK=true npm run build
      #     cd ..

      # 10. Deploy all apps
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting:angularHostApp
          firebase deploy --only hosting:angularRemoteApp
          # firebase deploy --only hosting:reactHostApp
          # firebase deploy --only hosting:reactRemoteApp
          firebase deploy --only hosting:vueHostApp
          firebase deploy --only hosting:vueRemoteApp
